/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as StudentOrganizationsRouteImport } from './routes/student-organizations'
import { Route as StackMapRouteImport } from './routes/stack-map'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as LeadershipAcademyRouteImport } from './routes/leadership-academy'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as IntelligenceStackRouteImport } from './routes/intelligence-stack'
import { Route as InspirationsRouteImport } from './routes/inspirations'
import { Route as IllinoisTechRouteImport } from './routes/illinois-tech'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as AutonomousVehiclesRouteImport } from './routes/autonomous-vehicles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as FriendsSlugRouteImport } from './routes/friends.$slug'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminContactRouteImport } from './routes/admin/contact'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentOrganizationsRoute = StudentOrganizationsRouteImport.update({
  id: '/student-organizations',
  path: '/student-organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const StackMapRoute = StackMapRouteImport.update({
  id: '/stack-map',
  path: '/stack-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipAcademyRoute = LeadershipAcademyRouteImport.update({
  id: '/leadership-academy',
  path: '/leadership-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceStackRoute = IntelligenceStackRouteImport.update({
  id: '/intelligence-stack',
  path: '/intelligence-stack',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationsRoute = InspirationsRouteImport.update({
  id: '/inspirations',
  path: '/inspirations',
  getParentRoute: () => rootRouteImport,
} as any)
const IllinoisTechRoute = IllinoisTechRouteImport.update({
  id: '/illinois-tech',
  path: '/illinois-tech',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AutonomousVehiclesRoute = AutonomousVehiclesRouteImport.update({
  id: '/autonomous-vehicles',
  path: '/autonomous-vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PostsRoute,
} as any)
const FriendsSlugRoute = FriendsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FriendsRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/autonomous-vehicles': typeof AutonomousVehiclesRoute
  '/avatar': typeof AvatarRoute
  '/contact': typeof ContactRoute
  '/friends': typeof FriendsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/illinois-tech': typeof IllinoisTechRoute
  '/inspirations': typeof InspirationsRoute
  '/intelligence-stack': typeof IntelligenceStackRoute
  '/journey': typeof JourneyRoute
  '/leadership-academy': typeof LeadershipAcademyRoute
  '/posts': typeof PostsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/stack-map': typeof StackMapRoute
  '/student-organizations': typeof StudentOrganizationsRoute
  '/test': typeof TestRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/friends/$slug': typeof FriendsSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/autonomous-vehicles': typeof AutonomousVehiclesRoute
  '/avatar': typeof AvatarRoute
  '/contact': typeof ContactRoute
  '/friends': typeof FriendsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/illinois-tech': typeof IllinoisTechRoute
  '/inspirations': typeof InspirationsRoute
  '/intelligence-stack': typeof IntelligenceStackRoute
  '/journey': typeof JourneyRoute
  '/leadership-academy': typeof LeadershipAcademyRoute
  '/posts': typeof PostsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/stack-map': typeof StackMapRoute
  '/student-organizations': typeof StudentOrganizationsRoute
  '/test': typeof TestRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/friends/$slug': typeof FriendsSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/autonomous-vehicles': typeof AutonomousVehiclesRoute
  '/avatar': typeof AvatarRoute
  '/contact': typeof ContactRoute
  '/friends': typeof FriendsRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/illinois-tech': typeof IllinoisTechRoute
  '/inspirations': typeof InspirationsRoute
  '/intelligence-stack': typeof IntelligenceStackRoute
  '/journey': typeof JourneyRoute
  '/leadership-academy': typeof LeadershipAcademyRoute
  '/posts': typeof PostsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/stack-map': typeof StackMapRoute
  '/student-organizations': typeof StudentOrganizationsRoute
  '/test': typeof TestRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/friends/$slug': typeof FriendsSlugRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/autonomous-vehicles'
    | '/avatar'
    | '/contact'
    | '/friends'
    | '/gallery'
    | '/illinois-tech'
    | '/inspirations'
    | '/intelligence-stack'
    | '/journey'
    | '/leadership-academy'
    | '/posts'
    | '/projects'
    | '/resume'
    | '/skills'
    | '/stack-map'
    | '/student-organizations'
    | '/test'
    | '/admin/contact'
    | '/admin/integrations'
    | '/admin/login'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/projects'
    | '/friends/$slug'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/autonomous-vehicles'
    | '/avatar'
    | '/contact'
    | '/friends'
    | '/gallery'
    | '/illinois-tech'
    | '/inspirations'
    | '/intelligence-stack'
    | '/journey'
    | '/leadership-academy'
    | '/posts'
    | '/projects'
    | '/resume'
    | '/skills'
    | '/stack-map'
    | '/student-organizations'
    | '/test'
    | '/admin/contact'
    | '/admin/integrations'
    | '/admin/login'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/projects'
    | '/friends/$slug'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/autonomous-vehicles'
    | '/avatar'
    | '/contact'
    | '/friends'
    | '/gallery'
    | '/illinois-tech'
    | '/inspirations'
    | '/intelligence-stack'
    | '/journey'
    | '/leadership-academy'
    | '/posts'
    | '/projects'
    | '/resume'
    | '/skills'
    | '/stack-map'
    | '/student-organizations'
    | '/test'
    | '/admin/contact'
    | '/admin/integrations'
    | '/admin/login'
    | '/admin/media'
    | '/admin/posts'
    | '/admin/projects'
    | '/friends/$slug'
    | '/posts/$slug'
    | '/projects/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AutonomousVehiclesRoute: typeof AutonomousVehiclesRoute
  AvatarRoute: typeof AvatarRoute
  ContactRoute: typeof ContactRoute
  FriendsRoute: typeof FriendsRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  IllinoisTechRoute: typeof IllinoisTechRoute
  InspirationsRoute: typeof InspirationsRoute
  IntelligenceStackRoute: typeof IntelligenceStackRoute
  JourneyRoute: typeof JourneyRoute
  LeadershipAcademyRoute: typeof LeadershipAcademyRoute
  PostsRoute: typeof PostsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResumeRoute: typeof ResumeRoute
  SkillsRoute: typeof SkillsRoute
  StackMapRoute: typeof StackMapRoute
  StudentOrganizationsRoute: typeof StudentOrganizationsRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-organizations': {
      id: '/student-organizations'
      path: '/student-organizations'
      fullPath: '/student-organizations'
      preLoaderRoute: typeof StudentOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack-map': {
      id: '/stack-map'
      path: '/stack-map'
      fullPath: '/stack-map'
      preLoaderRoute: typeof StackMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership-academy': {
      id: '/leadership-academy'
      path: '/leadership-academy'
      fullPath: '/leadership-academy'
      preLoaderRoute: typeof LeadershipAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence-stack': {
      id: '/intelligence-stack'
      path: '/intelligence-stack'
      fullPath: '/intelligence-stack'
      preLoaderRoute: typeof IntelligenceStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirations': {
      id: '/inspirations'
      path: '/inspirations'
      fullPath: '/inspirations'
      preLoaderRoute: typeof InspirationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/illinois-tech': {
      id: '/illinois-tech'
      path: '/illinois-tech'
      fullPath: '/illinois-tech'
      preLoaderRoute: typeof IllinoisTechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autonomous-vehicles': {
      id: '/autonomous-vehicles'
      path: '/autonomous-vehicles'
      fullPath: '/autonomous-vehicles'
      preLoaderRoute: typeof AutonomousVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof PostsRoute
    }
    '/friends/$slug': {
      id: '/friends/$slug'
      path: '/$slug'
      fullPath: '/friends/$slug'
      preLoaderRoute: typeof FriendsSlugRouteImport
      parentRoute: typeof FriendsRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminContactRoute: typeof AdminContactRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContactRoute: AdminContactRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface FriendsRouteChildren {
  FriendsSlugRoute: typeof FriendsSlugRoute
}

const FriendsRouteChildren: FriendsRouteChildren = {
  FriendsSlugRoute: FriendsSlugRoute,
}

const FriendsRouteWithChildren =
  FriendsRoute._addFileChildren(FriendsRouteChildren)

interface PostsRouteChildren {
  PostsSlugRoute: typeof PostsSlugRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsSlugRoute: PostsSlugRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AutonomousVehiclesRoute: AutonomousVehiclesRoute,
  AvatarRoute: AvatarRoute,
  ContactRoute: ContactRoute,
  FriendsRoute: FriendsRouteWithChildren,
  GalleryRoute: GalleryRoute,
  IllinoisTechRoute: IllinoisTechRoute,
  InspirationsRoute: InspirationsRoute,
  IntelligenceStackRoute: IntelligenceStackRoute,
  JourneyRoute: JourneyRoute,
  LeadershipAcademyRoute: LeadershipAcademyRoute,
  PostsRoute: PostsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResumeRoute: ResumeRoute,
  SkillsRoute: SkillsRoute,
  StackMapRoute: StackMapRoute,
  StudentOrganizationsRoute: StudentOrganizationsRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
